#ifndef FRAMEBUFFER_H
#define FRAMEBUFFER_H

#define PDSIM_SCREEN_WIDTH 400
#define PDSIM_SCREEN_HEIGHT 240
#define PDSIM_FRAMEBUFFER_BYTES_PER_ROW 52
#define PDSIM_FRAMEBUFFER_SIZE (PDSIM_FRAMEBUFFER_BYTES_PER_ROW * PDSIM_SCREEN_HEIGHT)

#endif
